### PR TITLE
Feature/mdoc microsite

### PR DESCRIPTION
**Pull request by olafbey**
Hello Gabriel, my first pr :-).

### CODE REVIEW

**Comment by gvolpe** [comment]
Great! :rocket: 

Can you try removing [this line](https://github.com/profunktor/http4s-jwt-auth/blob/master/build.sbt#L6)? It seems there's a collision with the `crossScalaVersions`.

You can also update the `crossScalaVersions` to 2.13.1 :)

**Comment by gvolpe** [comment]
You can also remove the `micrositePalette := Map( ... )` :)

**Comment by gvolpe** [comment]
Maybe we need to update the `kind-projector` plugins as well, but I'm not sure whether that's needed. 

If the issue remains, let's do that. You can look at [this commit](https://github.com/profunktor/fs2-rabbit/pull/297/commits/77c00d4ecfa31d7433140f3b4a594180f27a380b) where I fixed the same issue in other library.

**Comment by olafbey** [comment]
Gabriel, I deleted the scalaVersion from the top and modified the microsite-task. I tried to adjust the scala-version to 2.13.1 and played with kindProjection according to your changes in fs2rabbit, but it made everything worse :-(. But I think, the current commit should work. How should I go on?

**Comment by gvolpe** [comment]
@olafbey awesome work! The new microsite is now up :) https://http4s-jwt-auth.profunktor.dev/

**Pull request merged**
